import { Memory } from "@/types";

export const demoMemories: Memory[] = [
  {
    id: "mem-01",
    category: "Audience",
    title: "Practical educational content generates stronger saves for this audience",
    description:
      "When posts break down concrete website audits, checklists, and actionable UX fixes, small-business founders bookmark the content at a 3.4x higher rate than theoretical advice.",
    confidence: 84,
    evidenceCount: 6,
    firstObserved: "21 days ago",
    lastUpdated: "2 days ago",
    supportingPostIds: ["post-04", "post-05", "post-08", "post-11", "post-17", "post-20"],
    supportingExperimentIds: ["exp-02"],
    influencedCount: 9,
    status: "Strengthened",
    tags: ["High Saves", "Founders", "Actionable"],
  },
  {
    id: "mem-02",
    category: "Content",
    title: "Question-based hooks generate significantly more comments and discussions",
    description:
      "Framing the hook as an introspective business dilemma ('Is your website bounce rate costing you leads?') triggers immediate founder responses and peer discussions in the comment section.",
    confidence: 91,
    evidenceCount: 7,
    firstObserved: "12 days ago",
    lastUpdated: "Today",
    supportingPostIds: ["post-04", "post-09", "post-13", "post-16", "post-18", "post-20"],
    supportingExperimentIds: ["exp-01", "exp-05"],
    influencedCount: 14,
    status: "Strengthened",
    tags: ["High Comments", "Hooks", "Engagement"],
  },
  {
    id: "mem-03",
    category: "Performance",
    title: "Generic service promotion underperforms across all reach and retention metrics",
    description:
      "Posts announcing agency openings, generic capability brochures, or direct sales pitches receive 68% fewer views and negligible saves compared to value-first educational content.",
    confidence: 79,
    evidenceCount: 5,
    firstObserved: "26 days ago",
    lastUpdated: "5 days ago",
    supportingPostIds: ["post-01", "post-03", "post-06", "post-12", "post-19"],
    supportingExperimentIds: ["exp-03"],
    influencedCount: 7,
    status: "Active",
    tags: ["Underperforming", "Promotion", "Negative Signal"],
  },
  {
    id: "mem-04",
    category: "Performance",
    title: "Evening publishing (7:00 PM – 8:30 PM) appears to generate stronger reach",
    description:
      "Target audience founders and business owners consume educational Instagram content during their evening wind-down hours, generating 35% higher initial velocity within the first 60 minutes.",
    confidence: 72,
    evidenceCount: 4,
    firstObserved: "16 days ago",
    lastUpdated: "3 days ago",
    supportingPostIds: ["post-15", "post-16", "post-18", "post-20"],
    supportingExperimentIds: ["exp-04"],
    influencedCount: 6,
    status: "Active",
    tags: ["Posting Time", "Reach Velocity", "Evenings"],
  },
  {
    id: "mem-05",
    category: "Content",
    title: "Website transformation and tear-down case studies drive highest inbound bookmarking",
    description:
      "Demonstrating before-and-after conversion metrics for real local business categories (e.g. dental clinic, law firm) establishes undeniable agency authority and high shareability.",
    confidence: 88,
    evidenceCount: 4,
    firstObserved: "18 days ago",
    lastUpdated: "4 days ago",
    supportingPostIds: ["post-07", "post-09", "post-15", "post-18"],
    influencedCount: 8,
    status: "Strengthened",
    tags: ["Case Studies", "Tear Downs", "Authority"],
  },
  {
    id: "mem-06",
    category: "Audience",
    title: "Audience consists of non-technical founders seeking business ROI over dev jargon",
    description:
      "Terms like 'Next.js server actions' or 'database indexing' receive blank stares; framing the exact same technical concepts around 'mobile page load drops 20% bounce rate' generates immediate traction.",
    confidence: 94,
    evidenceCount: 8,
    firstObserved: "28 days ago",
    lastUpdated: "1 day ago",
    supportingPostIds: ["post-05", "post-08", "post-13", "post-14", "post-16"],
    influencedCount: 16,
    status: "Confirmed",
    tags: ["Tone", "Language", "ROI Focus"],
  },
  {
    id: "mem-07",
    category: "Brand",
    title: "Strict brand constraint: Never use shallow clickbait; maintain high technical integrity",
    description:
      "Byte Brothers insists on clean, respectable authority. Hooks must promise only what the subsequent video or carousel genuinely delivers in depth.",
    confidence: 98,
    evidenceCount: 3,
    firstObserved: "30 days ago",
    lastUpdated: "8 days ago",
    supportingPostIds: ["post-02", "post-10", "post-17"],
    influencedCount: 22,
    status: "Confirmed",
    tags: ["Core Value", "Integrity", "Guideline"],
  },
  {
    id: "mem-08",
    category: "Feedback",
    title: "Direct call-to-actions convert better when framed as an interactive diagnostic audit",
    description:
      "Encouraging followers to comment a specific keyword (e.g. 'AUDIT') to inspect their own homepage converts 3.2x higher than asking them to 'Click link in bio to schedule a discovery call'.",
    confidence: 86,
    evidenceCount: 3,
    firstObserved: "14 days ago",
    lastUpdated: "Today",
    supportingPostIds: ["post-11", "post-13", "post-20"],
    supportingExperimentIds: ["exp-05"],
    influencedCount: 11,
    status: "Strengthened",
    tags: ["CTA Strategy", "Lead Gen", "Comments to DM"],
  },
  {
    id: "mem-09",
    category: "Strategy",
    title: "Problem-focused educational Reels represent the brand's primary lead generation engine",
    description:
      "Combining a business-pain hook with a 30-second concrete visual breakdown yields the highest combined comment velocity, save retention, and profile visits for Byte Brothers.",
    confidence: 87,
    evidenceCount: 8,
    firstObserved: "15 days ago",
    lastUpdated: "Today",
    supportingPostIds: ["post-04", "post-07", "post-09", "post-13", "post-15", "post-16", "post-18", "post-20"],
    supportingExperimentIds: ["exp-01", "exp-02", "exp-05"],
    influencedCount: 18,
    status: "Strengthened",
    tags: ["Core Strategy", "Reel Format", "High Conversion"],
  },
];
