import { SocialPost } from "@/types";

export const demoHistoricalPosts: SocialPost[] = [
  {
    id: "post-01",
    postNumber: "Post #01",
    publishedAt: "28 days ago",
    format: "Static Post",
    topic: "Agency Announcement",
    hook: "We build websites that scale your business.",
    caption: "Looking for a new website? Byte Brothers offers custom web design and engineering.",
    views: 1200,
    likes: 42,
    comments: 3,
    saves: 4,
    shares: 1,
    engagementRate: 4.16,
  },
  {
    id: "post-02",
    postNumber: "Post #02",
    publishedAt: "26 days ago",
    format: "Carousel",
    topic: "Web Design Tips",
    hook: "5 design trends you should know for 2026.",
    caption: "Clean layouts, fast loading times, and intuitive navigation make all the difference.",
    views: 2400,
    likes: 110,
    comments: 12,
    saves: 45,
    shares: 14,
    engagementRate: 7.54,
  },
  {
    id: "post-03",
    postNumber: "Post #03",
    publishedAt: "25 days ago",
    format: "Static Post",
    topic: "Service Promotion",
    hook: "Our custom web dev packages start this month.",
    caption: "Book a discovery call with Byte Brothers today and upgrade your digital storefront.",
    views: 1100,
    likes: 31,
    comments: 2,
    saves: 3,
    shares: 0,
    engagementRate: 3.27,
  },
  {
    id: "post-04",
    postNumber: "Post #04",
    publishedAt: "23 days ago",
    format: "Reel",
    topic: "Business Pain Points",
    hook: "Is your website bounce rate costing you customer leads?",
    caption: "If users leave within 3 seconds, here are two immediate layout issues to inspect.",
    views: 5200,
    likes: 340,
    comments: 48,
    saves: 182,
    shares: 54,
    engagementRate: 12.0,
  },
  {
    id: "post-05",
    postNumber: "Post #05",
    publishedAt: "21 days ago",
    format: "Carousel",
    topic: "Educational Breakdown",
    hook: "Why 80% of local service websites fail to convert mobile visitors.",
    caption: "Mobile viewports require distinct CTA hierarchy. Swipe through the before & after.",
    views: 4800,
    likes: 290,
    comments: 34,
    saves: 210,
    shares: 61,
    engagementRate: 12.4,
  },
  {
    id: "post-06",
    postNumber: "Post #06",
    publishedAt: "20 days ago",
    format: "Static Post",
    topic: "Agency Promo",
    hook: "Why choose Byte Brothers for your next project?",
    caption: "We pride ourselves on clean code, responsive layouts, and transparent pricing.",
    views: 950,
    likes: 28,
    comments: 1,
    saves: 2,
    shares: 1,
    engagementRate: 3.36,
  },
  {
    id: "post-07",
    postNumber: "Post #07",
    publishedAt: "18 days ago",
    format: "Reel",
    topic: "Website Transformation",
    hook: "We redesigned this local dental clinic homepage. Here's what happened to bookings.",
    caption: "Removing friction from the primary appointment button increased mobile conversions by 38%.",
    views: 6400,
    likes: 420,
    comments: 52,
    saves: 290,
    shares: 88,
    engagementRate: 13.28,
  },
  {
    id: "post-08",
    postNumber: "Post #08",
    publishedAt: "17 days ago",
    format: "Carousel",
    topic: "SEO & Speed",
    hook: "3 free tools to test if your website is secretly sluggish.",
    caption: "PageSpeed Insights, GTmetrix, and WebPageTest. Bookmark this for your weekend check.",
    views: 5100,
    likes: 310,
    comments: 26,
    saves: 245,
    shares: 72,
    engagementRate: 12.8,
  },
  {
    id: "post-09",
    postNumber: "Post #09",
    publishedAt: "15 days ago",
    format: "Reel",
    topic: "Conversion Architecture",
    hook: "Are you making this hero section mistake on your homepage?",
    caption: "When visitors land on your site, do they immediately know what problem you solve?",
    views: 7100,
    likes: 510,
    comments: 76,
    saves: 330,
    shares: 95,
    engagementRate: 14.24,
  },
  {
    id: "post-10",
    postNumber: "Post #10",
    publishedAt: "14 days ago",
    format: "Static Post",
    topic: "Team Culture",
    hook: "Behind the screens at Byte Brothers HQ.",
    caption: "A peek at our developer setup while building client applications this week.",
    views: 1400,
    likes: 65,
    comments: 6,
    saves: 8,
    shares: 2,
    engagementRate: 5.78,
  },
  {
    id: "post-11",
    postNumber: "Post #11",
    publishedAt: "12 days ago",
    format: "Carousel",
    topic: "Lead Generation",
    hook: "The Anatomy of a High-Converting B2B Service Page.",
    caption: "Save this template if you're rebuilding your agency or consulting landing page.",
    views: 6200,
    likes: 380,
    comments: 42,
    saves: 315,
    shares: 82,
    engagementRate: 13.2,
  },
  {
    id: "post-12",
    postNumber: "Post #12",
    publishedAt: "11 days ago",
    format: "Static Post",
    topic: "Agency Promo",
    hook: "Need a modern web app? Byte Brothers is taking on 2 new clients.",
    caption: "DM us 'GROWTH' to book a strategic audit with our founders.",
    views: 1050,
    likes: 33,
    comments: 3,
    saves: 1,
    shares: 0,
    engagementRate: 3.52,
  },
  {
    id: "post-13",
    postNumber: "Post #13",
    publishedAt: "9 days ago",
    format: "Reel",
    topic: "Technical Friction",
    hook: "Why your contact form might be silently killing your customer pipeline.",
    caption: "We audited 30 local business websites: 60% had broken or confusing form validation.",
    views: 8200,
    likes: 590,
    comments: 89,
    saves: 380,
    shares: 114,
    engagementRate: 14.3,
  },
  {
    id: "post-14",
    postNumber: "Post #14",
    publishedAt: "8 days ago",
    format: "Carousel",
    topic: "Typography & Readability",
    hook: "Why font choice is costing you readability and trust.",
    caption: "Small business owners often pick stylish fonts over legible hierarchies. Here is the fix.",
    views: 4300,
    likes: 240,
    comments: 18,
    saves: 175,
    shares: 38,
    engagementRate: 10.95,
  },
  {
    id: "post-15",
    postNumber: "Post #15",
    publishedAt: "6 days ago",
    format: "Reel",
    topic: "Website Transformation",
    hook: "From confusing clutter to 2.4x more consultations: A local law firm redesign.",
    caption: "Clear headline + trust badges + singular direct booking call to action.",
    views: 8900,
    likes: 670,
    comments: 94,
    saves: 420,
    shares: 130,
    engagementRate: 14.76,
  },
  {
    id: "post-16",
    postNumber: "Post #16",
    publishedAt: "5 days ago",
    format: "Reel",
    topic: "Evening Publishing Experiment",
    hook: "Could 1 second of loading speed really save a small business $10,000?",
    caption: "Published at 7:45 PM: Core web vitals breakdown for non-technical founders.",
    views: 9400,
    likes: 710,
    comments: 105,
    saves: 460,
    shares: 142,
    engagementRate: 15.07,
  },
  {
    id: "post-17",
    postNumber: "Post #17",
    publishedAt: "4 days ago",
    format: "Carousel",
    topic: "Educational Checklist",
    hook: "The 7-point audit every founder should run on their website tonight.",
    caption: "No coding required. Check these 7 elements from your phone right now.",
    views: 7800,
    likes: 540,
    comments: 63,
    saves: 395,
    shares: 118,
    engagementRate: 14.3,
  },
  {
    id: "post-18",
    postNumber: "Post #18",
    publishedAt: "3 days ago",
    format: "Reel",
    topic: "Business Pain Points",
    hook: "How many customers did your homepage turn away today without you knowing?",
    caption: "Visitors bounce when value proposition is obscured. Here is how to fix your first screen fold.",
    views: 10200,
    likes: 820,
    comments: 118,
    saves: 512,
    shares: 165,
    engagementRate: 15.83,
  },
  {
    id: "post-19",
    postNumber: "Post #19",
    publishedAt: "2 days ago",
    format: "Static Post",
    topic: "Service Promotion",
    hook: "Ready to overhaul your digital presence this quarter?",
    caption: "Byte Brothers has 1 spot remaining for bespoke client engagements. Reach out.",
    views: 1350,
    likes: 41,
    comments: 4,
    saves: 5,
    shares: 1,
    engagementRate: 3.77,
  },
  {
    id: "post-20",
    postNumber: "Post #20",
    publishedAt: "1 day ago",
    format: "Reel",
    topic: "Educational / Problem Hook",
    hook: "Why having a 'Contact Us' page might actually be losing you leads.",
    caption: "Embedding contextual booking directly where the visitor learns about your offer converts 2x better.",
    views: 11400,
    likes: 910,
    comments: 132,
    saves: 580,
    shares: 184,
    engagementRate: 15.84,
  },
];
